name: av-jobathon-apr-2022
dependencies:
  - python=3.9
  - pip
  - pip:
    - pip==22.0.3
    - setuptools==60.8.2
    - wheel==0.37.1
    - ipykernel==6.9.0
    - numpy==1.22.2
    - pandas==1.4.1
    - matplotlib==3.5.1
    - seaborn==0.11.2
    - category-encoders==2.3.0
    - scikit-learn==1.0.2
    - xgboost==1.5.2
    - lightgbm==3.3.2
    - mxnet==1.9.0
    - tensorflow==2.8.0
